---
- name: sync last device to group
  bigip_configsync_actions:
    server: "{{ server_name }}"
    user: "{{ bigip_user }}"
    password: "{{ bigip_password }}"
    validate_certs: False
    device_group: "{{ bigip_device_group }}"
    sync_device_to_group: yes
  failed_when: "false"
...
