---
- hosts: "192.168.1.253"
  gather_facts: no
  connection: local

  tasks:

  - name: obtain f5 login credentials
    include_vars: ../f5-secrets.yml

  - name: obtain necessary variables
    include_vars: ../f5-vars.yml

  - include_role:
      name: newtenant
...
